name: laravel-model-schema-checker
type: php
docroot: public
php_version: "8.3"
webserver_type: nginx-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
database:
  type: mysql
  version: "8.0"
use_dns_when_possible: true
composer_version: "2"
web_environment:
- DRUSH_OPTIONS_URI=https://laravel-model-schema-checker.ddev.site